# Supabase local configuration
# This file configures the local Supabase instance

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

# Désactiver les services externes en local
[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

# Configuration SMS - Désactiver Twilio en local
[auth.sms]
enable_signup = true
enable_confirmations = true
# Désactiver le fournisseur SMS en local pour éviter les erreurs Twilio
# provider = "twilio"

[edge_runtime]
enabled = true

[analytics]
enabled = false
port = 54330
vector_port = 54331
# Désactiver l'analytics en local
[functions.evaluate-agricultural-rules]
enabled = true
verify_jwt = true
import_map = "./functions/evaluate-agricultural-rules/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/evaluate-agricultural-rules/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/evaluate-agricultural-rules/*.html" ]

[functions.send-wolof-tts-call]
enabled = true
verify_jwt = true
import_map = "./functions/send-wolof-tts-call/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-wolof-tts-call/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-wolof-tts-call/*.html" ]
